### ISSUE TITLE
gtk theme cannot be installed

### ISSUE THREAD

**Issue by Fabbe041** [Roboron3042/Cyberpunk-Neon#1]
Hi, I got a problem when I want to apply the gtk theme. 
I select the tar.gz file but then it says that I cannot install it 
plz help

**Comment by Legogris** [comment]
I had no issues with this. What happens when you run `tar xzf Cyberpunk-Neon-GTK.tar.gz -C ~/.themes/` and then look for the theme in `lxappearance`?

**Comment by Roboron3042** [comment]
Closing by lack of feedback.
