### ISSUE TITLE
Bug Ubuntu 20.10: Gray TopBar menu text

### ISSUE THREAD

**Issue by nitanmarcel** [Roboron3042/Cyberpunk-Neon#12]
The text in the drop-down menus from the top bar are gray and makes it hard to read them. I tried to play with the colors but I gave since I can't find the correct one. Any quick fix?

![image](https://user-images.githubusercontent.com/41646249/98036392-a3c12e80-1e22-11eb-8c14-3ff8490ce528.png)

**Comment by Roboron3042** [comment]
Is this a thing that only happens on GNOME drop down menus? Or does it also happens on others GTK applications? (I have not seen any yet)

**Comment by nitanmarcel** [comment]
> Is this a thing that only happens on GNOME drop down menus? Or does it also happens on others GTK applications? (I have not seen any yet)

It happens on other GTK applications too.

**Comment by Roboron3042** [comment]
Then the theme just needs an update. I will fix it soon.

**Comment by nitanmarcel** [comment]
> Then the theme just needs an update. I will fix it soon.

Awesome, thanks. Btw one question not related to this issue: How did you used separated icons for the app bar on the left?

**Comment by Roboron3042** [comment]
> Awesome, thanks. Btw one question not related to this issue: How did you used separated icons for the app bar on the left?

KDE Plasma lets you define custom icon for applications. This way you can overwrite the one provided by the icon theme.

**Comment by Roboron3042** [comment]
Sorry, I can't build the new themes. My systems freeze while compiling the themes with oomox :-/
