### ISSUE TITLE
Native Qt themes

### ISSUE THREAD

**Issue by Anomalocaridid** [Roboron3042/Cyberpunk-Neon#17]
To use the GTK theme for QT applications in my setup, I rely on qgtkstyle from qt5-style-plugins. However, this does not work with Qt6. I would greatly appreciate it if you created native Qt themes for this color scheme so that I could use it with both Qt5 and Qt6 applications.

**Comment by Roboron3042** [comment]
Hmm, I would rather wait for qt6ct to introduce a similar feature than investing lots and lots of time into a creating a full Qt6 theme.

Also, I don't use any Qt6 application myself so I'm not much motivated to do this yet. But I'm open to contributions if anyone want to take care of this.

**Comment by Roboron3042** [comment]
https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#QGtkStyle

> For Qt 6, it can be enabled by installing [qt6gtk2](https://aur.archlinux.org/packages/qt6gtk2/)AUR and choosing the qt6gtk2 style in [qt6ct](https://archlinux.org/packages/?name=qt6ct), or alternatively setting the following environment variable: QT_QPA_PLATFORMTHEME=gtk2

**Comment by Anomalocaridid** [comment]
Thank you. That solution works for me. I did not see that when I initially made this issue, so I wonder if that was added to that page recently.
