### ISSUE TITLE
[Request] Sidebar Support for telegram desktop Theme

### ISSUE THREAD

**Issue by SteveBlackHumor** [Roboron3042/Cyberpunk-Neon#19]
The current telegram theme doens't support sidebar colors, the sidebar it's still in blue and gray colors, which doens't fit the neon style theme. So I created a new version which does have mathcing colors. However, I think my design ability is limited, and I'm kinda a github noob who doesn't know much about pull request, so I would like to provide my version as a reference, really wish you can help with official sidebar support.

The sidebar colors can be found in Edit Color Palette by searching keyword "sideBar".

Here's how it looks like:
![Neon With Bar](https://user-images.githubusercontent.com/38856763/143722329-c977bc5a-3a6e-4c9e-9046-1462040517ef.png)

Here's the link to the edited theme:
https://t.me/addtheme/cyberpunk_neon_bar

Here's the theme file:
[cyberpunk_neon_bar.tdesktop-theme.zip](https://github.com/Roboron3042/Cyberpunk-Neon/files/7612457/cyberpunk_neon_bar.tdesktop-theme.zip)

**Comment by Roboron3042** [comment]
I didn't know about the sidebar, thank you.

Your design seems good, but I usually use pink for the active element only. I switched colours and also modified the selected  folder background for consistency in the official version.

By the way, how do you export the theme to a .zip file now? I can't find that option.

**Comment by SteveBlackHumor** [comment]
Thanks so much for your help. In settings > chat settings > edit theme > 3 dots right to the title "Edit Color Palette" > Export theme

![Export_Theme](https://user-images.githubusercontent.com/38856763/143950562-7148e710-e08a-468d-9abd-b4e564ab11e4.png)

**Comment by Roboron3042** [comment]
Thank your very much, I can now commit the exported file which was missing since the last update.
