### ISSUE TITLE
oomox theme file

### ISSUE THREAD

**Issue by Legogris** [Roboron3042/Cyberpunk-Neon#2]
@Roboron3042 It would be awesome if you could export and commit the oomox config for the theme :)

**Comment by Roboron3042** [comment]
I don't know how to export the oomox config (it doesn't seem there's an option for that in oomox).

But sadly, even if i knew, it isn't possible anymore. My HDD broke last month, and i lost that config. I could try and redo the theme, but i don't remember what variation of Materia I used as a base and/or others values I modified (or if I modified them at all).

**Comment by Legogris** [comment]
Aw shucks @Roboron3042 .
When I started oomox there was an "export" option in the menu - and if nothing else you could just take the folder under `~/.config`. There's docs on this in the oomox repo IIRC.

But thanks for the update regardless, I'll play around a bit, I might ping you if I come up with something nice in vibe with what you have here

**Comment by Roboron3042** [comment]
I only see 3 export buttons in oomox - "Export Theme", "Export Icons" and "Export Terminal". The first option is the one I used to generate the theme. 

I've looked at the docs and they say something about [exporting base 16 based themes](https://github.com/themix-project/oomox/wiki/How-to-import-and-export-Base16-themes-in-Themix-Oomox) but i'm pretty sure i didn't created Cyberpunk-Neon from a base16 theme - indeed i only used 6 colors, [the five colors from the Cybperunk Neon palette](https://www.color-hex.com/color-palette/61235) plus an extra color for darkest background (#000b1e). You can easily replicate the theme using those colors.

**Comment by Legogris** [comment]
I had it a bit wrong on being in the menu: https://github.com/themix-project/oomox/wiki/How-to-contribute-your-theme-from-Github-website
Basically they reside as folders in `~/.config/oomox/colors`.

**Comment by Roboron3042** [comment]
Okay, I have remade the oomox theme and comitted the config. However, now that you pointed me to that link, i'm thinking also on completing the Numix and Arc style and contributing the theme to oomox. What do you think?

**Comment by Legogris** [comment]
That would be great! I am sure there are others who appreciate this :)
(I have no affiliation with the oomox project if that wasn't clear)

**Comment by Roboron3042** [comment]
> I have no affiliation with the oomox project if that wasn't clear

I know, i just wanted some feedback :)

Numix and Arc variants are now completed and committed, and oomox theme configuration updated. I've also create the pull request to include Cyberpunk-Neon in oomox https://github.com/themix-project/oomox/pull/237

I guess i can close the issue xD

**Comment by actionless** [comment]
just a side note:
you can use Base16 Export to generate the base for colored Vim and other themes

**Comment by Roboron3042** [comment]
I know Vim can generate a default theme using the terminal colors. That, however, was not enough for me, I wanted to fine-tune it myself, and so I did!

This is the result: Before / After*
![Vim comparison](https://github.com/Roboron3042/Cyberpunk-Neon/blob/master/Resources/Screenshots/vim.png?raw=true)

I think i got that Cyberpunk-Neon feeling better (*The background in this comparison was set to grey instead of dark blue because I could not find a proper blue in the 256 colors for the background, but i guess you don't have to set it to any color if you have defined a background color for the terminal).
