### ISSUE TITLE
Unable to set all the terminal colors on xfce-terminal

### ISSUE THREAD

**Issue by AA1999** [Roboron3042/Cyberpunk-Neon#25]
It doesn't support that many colors in the preferences.
Is there any other way I can change the theme?
The terminal is the most feature-rich of all the listed terminals

**Comment by Roboron3042** [comment]
I just installed xfce4-terminal and there are 16 colours in the preferences, as usual. I don't know where are you looking.

P.D.: I don't think there is a more feature rich terminal than Konsole, it's a KDE application after all.
