### ISSUE TITLE
BetterDiscord transparent theme is not transparent

### ISSUE THREAD

**Issue by AA1999** [Roboron3042/Cyberpunk-Neon#26]
I tried both versions but used the transparent one first. It's not transparent.
I even tried copy-pasting the CSS into custom CSS and updating it.
This is my selected theme on BetterDiscord

![image](https://user-images.githubusercontent.com/14325650/156765402-1920468b-fc07-4e00-a8fb-4238c727de46.png)

**Comment by Roboron3042** [comment]
Can you give me information about your installation (it should be at the end of the config menu). In my discord it is working fine, this is driving me crazy.

Stable 117300 (cc0861f)
BetterDiscord 1.5.2
Host 0.0.17 Linux 64-Bit (5.16.10-Arch1-1)

**Comment by AA1999** [comment]
Stable 117300 (cc0861f)
BetterDiscord 1.5.2
Host 0.0.17 Linux 64-Bit (5.16.11-Arch1-2)

**Comment by Roboron3042** [comment]
Nothing wrong there then. Try cleaning your Betterdiscord cache (~/.config/BetterDiscord Installer), and try again.

Did you change the default image?

**Comment by AA1999** [comment]
No I didn't touch anything
I also cleared cache after exiting BetterDiscord but still the same

This is what it looks like:

![image](https://user-images.githubusercontent.com/14325650/156781836-afa0987c-9392-40c0-a8c5-4fdd5ba75ee5.png)

**Comment by AA1999** [comment]
Are you sure it's not the BetterDiscord folder instead of BetterDiscord Installer?

**Comment by Roboron3042** [comment]
Ok, you'll have to get your hands dirty to help me with this. 

1. Go to BetterDiscord Settings -> Development Settings -> Enable "DevTools"
2. Press CTRL+SHIFT+I to open the inspector.
3. At the right, a tree of html elements will be shown. I need you to tell me what the first element after the "<body>" tag is (in my case this is "<div id="app-mount" class="appMount-2yBXZl">). I'm interested to see if your value of "class" is different from mine...

**Comment by AA1999** [comment]
![image](https://user-images.githubusercontent.com/14325650/156820395-323f3bd9-eb7a-4b93-b4ae-bab545f9aa93.png)

**Comment by Roboron3042** [comment]
Ok, different class idea discarded. Please try adding this CSS at the end of the theme
```
.bg-1QIAus {
    background-color: transparent; 
}
.app-2CXKsg {
    /background-color: transparent;
}
.appMount-2yBXZl {
    background-color: transparent !important;
}
```

**Comment by AA1999** [comment]
Result: 

![image](https://user-images.githubusercontent.com/14325650/156828142-43d8f631-6da9-4533-b1a9-296afe78346e.png)

**Comment by Roboron3042** [comment]
Let's discard that it is just the image not being loaded
```
.appMount-2yBXZl {
    background-image: none !important;
    background-color: #ffffff !important;
}
```

**Comment by AA1999** [comment]
![image](https://user-images.githubusercontent.com/14325650/156829460-13d92e86-3917-4479-b1ce-01c685c456b6.png)

I suppose it's more transparent but at the same time it's not transparent enough

**Comment by Roboron3042** [comment]
It looks ok. The transparency is working (I'll admit that it has to be tweaked, but that's another problem) but the issue is that there is no background.

Hmm, I was sure imgur was a safe place to upload images... For the next step, try replacing the default image with a link to an image uploaded to discord.

**Comment by AA1999** [comment]
Yeah, that fixed it. Tysm.

**Comment by Roboron3042** [comment]
Than you for your report, I would never had find the cause if it wasn't for you.
