### ISSUE TITLE
Same color in the palette

### ISSUE THREAD

**Issue by t-h2o** [Roboron3042/Cyberpunk-Neon#29]
Hello !
Why in the [terminal-palette](https://github.com/Roboron3042/Cyberpunk-Neon/blob/master/terminal/terminal-palette), is there same color for `color 1` and `color 9` ?

```
...
# *color1:  #ff0000
...
# *color9:  #ff0000
...
```

**Comment by Roboron3042** [comment]
Colours 9-15 are supposed to be "bright" colours, but the cyberpunk-neon colour-scheme is already pretty bright, so there is no need for most of them, that's why they are the same.

**Comment by t-h2o** [comment]
With the `ncdu`, I cannot read output because the text is the same color as the background.

**Comment by Roboron3042** [comment]
I don't have problems with ncdu colours 
![imagen](https://user-images.githubusercontent.com/22756082/201471085-299cfd4e-9931-4152-8eea-1831a45af088.png)

**Comment by t-h2o** [comment]
Me yes:
![image](https://user-images.githubusercontent.com/90759286/201472752-4f051416-a25e-4c61-82a2-5c2e451e9e75.png)
 probably the problem is into my [configuration file](https://github.com/Roboron3042/Cyberpunk-Neon/blob/master/terminal/kitty/cyberpunk-neon.conf) of kitty.
 Which terminal emulator do you use ?

**Comment by Roboron3042** [comment]
I use alacritty or konsole, both behave the same.

My neofetch only shows one row of colours (¿?)
![imagen](https://user-images.githubusercontent.com/22756082/205598143-2a068e96-bb10-4028-a111-ae2ecb063be5.png)

**Comment by Roboron3042** [comment]
I changed the background color of kitty. That allows the text to being read!

It's a pitty kitty doesn't pick up the green, but oh well.
