### ISSUE TITLE
Remove MPD from topbar

### ISSUE THREAD

**Issue by zlehnherr1** [Roboron3042/Cyberpunk-Neon#33]
I want to remove the MPD from the top bar, I was able to remove some of the other items, such as mastodon and twitter from the bar fine, but when I removed what was the MPD, I still have the disconnected item at the top.

**Comment by zlehnherr1** [comment]
My config file (some of the icons did not loading right)
// -*- mode: json -*-

{
	"layer": "top",
	"position": "top",

	"modules-left": [
		"sway/workspaces",
		"custom/right-arrow-workspaces",
		"custom/mastodon",
		"custom/twitter",
		"custom/github",
		"custom/reddit",
		"custom/traktv",
		"custom/right-arrow-shortcuts",
		"mpd",
		"custom/right-arrow-mpd",
	],
	"modules-center": [
		"custom/left-arrow-clock",
		"clock",
		"custom/right-arrow-clock"
	],
	"modules-right": [
		"custom/left-arrow-pulse",
		"custom/mpd-vol",
		"pulseaudio",
		"custom/left-arrow-modules",
		"memory",
		"cpu",
		"temperature",
		"disk",
		"custom/pacman",
		"battery",
		"custom/left-arrow-tray",
		"tray",
		"custom/exit"
	],

	"custom/right-arrow-workspaces": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-shortcuts": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-mpd": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-clock": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-clock": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-pulse": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-modules": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-mpd": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-modules": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-tray": {
		"format": "",
		"tooltip": false
	},

	"sway/workspaces": {
		"disable-scroll": false,
		"format": "{name}"
	},
	"custom/github": {
		"format": "",
		"on-click": "xdg-open https://github.com",
		"tooltip": false
	},
	"custom/reddit": {
		"format": "樓",
		"on-click": "$TERM -e tuir",
		"tooltip": false
	},



	"clock": {
		"format": "{:%a. %d | %H:%M}",
		"tooltip": false,
		"on-click": "zim 'Tu Wiki' Journal:$(date +%Y):Week_$(date +%V)",
		"on-click-right": "zim 'Universidad' Journal:$(date +%Y):Week_$(date +%V)"
	},
	"custom/mpd-vol": {
		"interval": 5,
		"format": " {}",
		"exec": "mpc volume | tr -dc '0-9%'",
		"on-scroll-up": "mpc volume +10",
		"on-scroll-down": "mpc volume -10"
	},
	"pulseaudio": {
		"format": "{icon} {volume:2}% {format_source}",
		"format-bluetooth": "{icon}  {volume}%",
		"format-muted": "MUTE",
		"format-source": "  {volume}%",
		"format-source-muted": " ",
		"format-icons": {
			"headphones": "",
			"default": [
				"",
				"",
				""
			]
		},
		"scroll-step": 5,
		"on-click-right": "amixer set Capture toggle",
		"on-click": "pavucontrol"
	},
	"memory": {
		"interval": 5,
		"format": " {}%",
		"on-click": "$TERM -e htop"
	},
	"cpu": {
		"interval": 5,
        "format": " {usage}%",
		"on-click": "$TERM -e htop"
	},
    "temperature": {
        "critical-threshold": 75,
        "format": " {temperatureC}°C"
    },
	"battery": {
		"states": {
			"good": 95,
			"warning": 30,
			"critical": 15
		},
		"format": "{icon} {capacity}%",
		"format-icons": [
			"",
			"",
			"",
			"",
			""
		]
	},
	"disk": {
		"interval": 5,
		"format": " {percentage_used}%",
		"path": "/",
		"on-click": "dolphin"
	},
	"custom/pacman": {
		"format": " {}",
		"interval": 3600, // every hour
		"exec": "checkupdates | wc -l", // # of updates
		"exec-if": "exit 0", // always run; consider advanced run conditions
		"on-click": "$TERM -e up; pkill -SIGRTMIN+8 waybar", // update system
		"signal": 8,
	},
	"tray": {
		"icon-size": 20,
		"spacing": 10
	},
	"custom/exit": {
		"tooltip": false,
		"format": "⏻",
		"on-click": "swaymsg exit",
		"on-click-right": "systemctl poweroff",
		"on-click-middle": "systemctl reboot"

**Comment by zlehnherr1** [comment]
My config file
[config.txt](https://github.com/Roboron3042/Cyberpunk-Neon/files/10415175/config.txt)

**Comment by Roboron3042** [comment]
Simply remove "mpd" and "custom/right-arrow-mpd" from "modules-left"

**Comment by zlehnherr1** [comment]
That worked! But now there is a grey background at the end of the arrow, is there a way to make that blend in with the darker color in the center portion?

**Comment by Roboron3042** [comment]
Either correct the styles in the .css file or replace "custom/right-arrow-shortcuts" with "custom/right-arrow-clock"
