### ISSUE TITLE
Webcord compatibility

### ISSUE THREAD

**Issue by Anomalocaridid** [Roboron3042/Cyberpunk-Neon#36]
The Discord themes almost work perfectly in Webcord, an alternative Discord client. However, a few things are incorrectly styled because Webcord needs the variables defined in the `html` selector to be in the `:root` selector instead.

For more information, please see this issue: SpacingBat3/Webcord#302

**Comment by Roboron3042** [comment]
Alright, I don't see anything wrong with changing the selector so this goes in.

Sorry for taking so long.
