### ISSUE TITLE
Hola, he tornado mi Suru++ compatible con tu tema y te he dado un homenaje

### ISSUE THREAD

**Issue by gusbemacbe** [Roboron3042/Cyberpunk-Neon#4]
¡Hola @Roboron3042 !

He añadido el soporte del [Suru++ 30](https://github.com/gusbemacbe/suru-plus) para Cyberpunk Neon. Los iconos de 16px y las carpetas han recibido los gradientes de Cyberpunk Neon. Suru++ siempre fue cyberpunk y futurista desde la versión 20. 

En homenaje a ti, aunque seas español, no sé donde vives, pero he escogido Barcelona o Bilbao o Madrid, pero he votado Barcelona para nombrar la próxima versión del Suru++ que he lanzado hoy. 

Puedes ver en la tercera captura de pantalla en mi producto en el OpenDesktop: https://www.opendesktop.org/p/1238162/

Las próximas semanas agregaré el soporte de Cyberpunk Neon para [Suru++ Asprómauros](https://github.com/gusbemacbe/suru-plus-aspromauros).

Espero que te gustes.

**Comment by Roboron3042** [comment]
¡Hola @gusbemacbe !

Gracias por el soporte a Cyberpunk-Neon y muchas gracias por el homenaje :-) (Aunque Barcelona está más bien en la otra punta del país xD).

He estado probando el tema de iconos, y la verdad es que se ve bastante bien. No obstante, he sido incapaz de cambiar el color de las carpetas a "cyberneon" - cuando uso el script "suru-plus-folders" todo parece funcionar porque no devuelve ningún error, pero nada cambia, escoja el color que escoja.

Por lo pronto, lo añadiré al README para que todo el mundo lo sepa. Mantenme informado sobre la versión de Asprómauros, porque creo que encajará mejor con mi visión del tema.

Gracias por el trabajo.

**Comment by gusbemacbe** [comment]
> No obstante, he sido incapaz de cambiar el color de las carpetas a "cyberneon" - cuando uso el script "suru-plus-folders" todo parece funcionar porque no devuelve ningún error, pero nada cambia, escoja el color que escoja.

Voy a investigar ahora.

**Comment by gusbemacbe** [comment]
He encontrado el error:

https://github.com/gusbemacbe/suru-plus-folders/blob/c3447ee46ffb9d199b81c801241f334e041a636b/suru-plus-folders#L256

Voy a corregir ahora.

**Comment by gusbemacbe** [comment]
Ahora funciona:

![image](https://user-images.githubusercontent.com/2257024/56911331-165d8b00-6a83-11e9-9089-65dbb48fe497.png)

**Comment by gusbemacbe** [comment]
Hola @Roboron3042 !

> Por lo pronto, lo añadiré al README para que todo el mundo lo sepa. Mantenme informado sobre la versión de Asprómauros, porque creo que encajará mejor con mi visión del tema. Todos los iconos fueron re-coloridos con los "cybercolores". 

He llevado dos meses para purificar los códigos del SVG en todos los iconos, incluyendo los nuevos de Papirus.

Come te he prometido, finalmente he lanzado la nueva oficial de Suru++ Asprómauros, agregando el soporte de gradientes, incluye el Cyberpunk Neon, para todos los iconos, incluyendo `actions`, `emblems`, `panel` y `status`, con sus carpetas `symbolic`. Cuando quieres aplicar el gradiente Cyberpunk Neon, ejecuta el comando:

```bash
cd Suru++\ Asprómauros
sed --in-place --follow-symlinks 's/fill="currentColor" class="ColorScheme-Text"/fill="url(#cyberneon)" class="ColorScheme-Text"/g' **/*.svg
sed --in-place --follow-symlinks 's/stroke="currentColor" class="ColorScheme-Text"/stroke="url(#cyberneon)" class="ColorScheme-Text"/g' **/*.svg
```

Si quieres cambiar de color verde para otro color del Cyberpunk Neon, ejecuta:

```bash
sed --in-place --follow-symlinks 's/color: #1AD6AB;/color: #[tu_color_favorito];/g' **/*.svg
```

Aquí están las previsiones:

![Page 1](https://user-images.githubusercontent.com/2257024/58935959-018cab00-8745-11e9-9883-5f8214b8d850.jpg)

![Page 2](https://user-images.githubusercontent.com/2257024/58935970-081b2280-8745-11e9-90d3-76cc9bc6d49e.jpg)

![Page 3](https://user-images.githubusercontent.com/2257024/58935979-0e110380-8745-11e9-893b-1b7edcfb4f4f.jpg)

**Comment by Roboron3042** [comment]
Oops, leí esto justo después de probarlo (el pull request de oomox iba primero en mi buzón de correo), y ya te dejé [una issue](https://github.com/gusbemacbe/suru-plus-aspromauros/issues/11). 

Así que ya he estado probándolo, aunque no sabía lo del gradiente. Pero soy feliz con la versión monocromática, era justo lo que necesitaba :-)

De nuevo muchas gracias por tu trabajo @gusbemacbe, es excelente. Ya he actualizado el README para informar de los nuevos iconos (y señarlarlos como preferidos). ¿Tal vez debería incluir información sobre los comandos necesarios para aplicar el tema y los gradientes a los iconos?

¡Buen trabajo!
