### ISSUE TITLE
[Bug] El texto y el marcador tienen mismo color, dificultando la legibilidad

### ISSUE THREAD

**Issue by gusbemacbe** [Roboron3042/Cyberpunk-Neon#5]
Hola @Roboron3042 !

Ve la captura de pantalla:

![image](https://user-images.githubusercontent.com/2257024/57159979-e2090800-6dbd-11e9-83ed-a1f158b553a0.png)

**Comment by Roboron3042** [comment]
Esto parece ser un problema con Materia (Ver: https://github.com/nana-4/materia-theme/issues/355).
Voy a hacer un commit que cambiará el texto de selección del mismo color, a un color parecido (tal como se muestra en la imagen del issue), así que esto no estará realmente solucionado hasta que Materia se actualice. Mientras tanto si es mucha molestia puede usar las otras variantes (Arc/Numix).

**Comment by Roboron3042** [comment]
Finalmente puedo cerrar esto. En la última actualización, el texto y el marcador son de diferente color.
