### ISSUE TITLE
Kvantum Materia Dark no se integra

### ISSUE THREAD

**Issue by Zardoz89** [Roboron3042/Cyberpunk-Neon#7]
Buenas. He probado a seguir tus instrucciones, instalando el susodicho tema de Kvantum y no usa para nada el esquema de colores. Utiliza su propoos colores en tonos de gris oscuro.

¿Hay que realizar algo más para que se integre bien?

![imagen](https://user-images.githubusercontent.com/888483/60570457-ea57d200-9d71-11e9-8af4-4b96adb7f3fc.png)

**Comment by Roboron3042** [comment]
Hola. Los temas de Kvantum no admiten cambios en el esquema de colores (porque están basados en SVG). Si quieres usar un esquema de colores como Cyberpunk Neon no puedes usar Kvantum.

**Comment by Zardoz89** [comment]
¿Entonces por que en las instrucciones recomiendas que se instale ese tema de Kvantum ?

> You can use the KDE color scheme with any theme, as long as they are not kvantum themes. For consistency is better to install Materia-Dark for KDE (or any of the QT versions of the GTK variants) to fit with gtk theme.

**Comment by Roboron3042** [comment]
Yo no lo recomiendo, viene en el texto que has citado: "You can use the KDE color scheme with any theme, **as long as they are not kvantum themes**".

Materia está disponible en dos versiones, una es de kvantum y otra no. En Arch Linux por ejemplo, el paquete `materia-kde` te instalará la versión normal (no kvantum), mientras que instalar `kvantum-theme-materia` te instalará la versión de kvantum.

Pero vaya, simplemente menciono Materia-Dark por consistencia (mi tema original de GTK es Materia Cyberpunk Neon, aunque ya están disponible Numix y Arc), en la práctica puedes usar el tema que quieras, siempre que no sea kvantum.

**Comment by Zardoz89** [comment]
Cierto... no se leer.
